name: Build Solution

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet
        run: nuget restore src/begeerte_ark_survival_ascended.sln

      - name: Build
        run: |
          msbuild src/begeerte_ark_survival_ascended.sln ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /m

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/Release/**
